#ifndef OPENESPRESSOPROFILER_CONFIG_H
#define OPENESPRESSOPROFILER_CONFIG_H

#define LED_PIN 2
#define PRESSURE_PIN 32

#define R1_OHMS 10000
#define R2_OHMS 15000

#define TRANSDUCER_MAX_PSI 200
#define TRANSDUCER_MIN_V 0.5
#define TRANSDUCER_MAX_V 4.5

#endif //OPENESPRESSOPROFILER_CONFIG_H
